### ISSUE TITLE
Instructions on install

### ISSUE THREAD

**Issue by nevos** [build2be/drupal-8-rest-angularjs#1]
I started this project but I'm not sure what is needed in terms of configuration
Going to <my-d8site>/app/index.html site/app/index.html I get nothing: see attached
![untitled-1](https://cloud.githubusercontent.com/assets/1281931/5939571/905f87fc-a70d-11e4-9026-216984eb13ba.jpg)

**Comment by clemens-tolboom** [comment]
Have you ran `npm install` next `npm start'?

Next you have to symlink the app into Drupal 8 root.

Next add "Rest export Display" to view on /node path

**Comment by clemens-tolboom** [comment]
Hope the added instructions help.

**Comment by nevos** [comment]
yes, these instructions helped. Thanks.

1. Still can't see the taxonomies on the article node.
2. Search and menu are not functional on my install.
3. commects are not active on my angular app install.

Further config details:
1. create an article and move it to the front page.
2. Add users can access their account in permissions.
3. the create taxonomy/list/% view + REST instruction is a little obscure. I've duplicated the default taxonomy view and renamed the path. This had no effect on displaying the terms.

**Comment by clemens-tolboom** [comment]
Let's close this and make more details issue (we mostly did :)

I've now added the view for taxonomy/list (it's still on develop) and I'm still learning.

Will probably merge to master tomorrow but that needs a better README
