### ISSUE TITLE
non functional elements

### ISSUE THREAD

**Issue by nevos** [build2be/drupal-8-rest-angularjs#4]
Hi,
I have this app partially working in displaying the list offront nodes and a single node, which is also pulling the user name and date created.

Otherwise:
I don't get the terms of a node (although the iteration revelas te number of terms), and the menu and search don't seem to work for me.
Thanks for this project.

N.

**Comment by clemens-tolboom** [comment]
Hi @nevos thanks for testing.

I've added some hints to the blocks. Or is that still on develop branch?

The terms don't work if there is no good view on term/list. See #5

**Comment by clemens-tolboom** [comment]
Merged all to master. Release 0.0.3 works on my drupal install. Feel free to ask about the specifics but I prefer a better README.md PR

**Comment by clemens-tolboom** [comment]
@nevos master works for node, node/add, node/nid (with comments) and node-lifecycle.

I close this issue now. Please test more and file small independent bugs :)
